server:
  port: 8080

# spring
spring:
  application:
    name: computer-shop
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/computermall?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: lq0522
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 5MB

# mybatis
mybatis:
  type-aliases-package: com.qun.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰命名

# 打印SQL日志
#logging:
#  level:
#    com.qun.mapper: debug


lupus:
  jwt:
    secret: f4e2e52034348fhf86b6lupus77cde581cef9eb5
    # token有效时长，7天 单位秒
    expire: 604800
    header: Authorization
