server:
  port: 8080

# spring
spring:
  application:
    name: computer-shop
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/computermall?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: lq0522
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 5MB

# mybatis
mybatis:
  type-aliases-package: com.qun.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰命名

# 打印SQL日志
#logging:
#  level:
#    com.qun.mapper: debug


lupus:
  jwt:
    secret: f4e2e52034348fhf86b6lupus77cde581cef9eb5
    # token有效时长，7天 单位秒
    expire: 604800
    header: Authorization

alipay:
  appId: 2021000117626364
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjWc1kubZCJbcC+0IOeaJaLPBBesj23C9WlZlJfymtrYUNxdXh+bxYPRyjysQE6mmlcf6X0A9OTSY1XVOVksUsitOxqM+jO31xKOEa9BsiHJn2nojzxpqeYugRwUG+S8OfDJPOglvUU3YEU2B+GN0FYdDT8hvryEs/uyCdQhcXS54vL3uXy2QVRIVhgpPWYHP660elrsBv4J/nyc3VdU9HiXFNHEML3Fm2ThTmPntLf0jA0nCKHzsfQfqZ8MZI4PpTK4Jwa9/vdFViYhgABtQVZtIzm4snXP6BFb8tHx7TWYrUKzhGH/qnZUSfm27mULXxG3Nt8+5ayVSKPrS9MqivAgMBAAECggEAJzRZYFBWFuAYYWXOP80fkwbwDrcaXm0QC3bSGFqltSJNKbYOlDKs6nyYUBNNImTkQCnw0ZzE36USg4JHmkFkg0E6d4wtcV7Ix4zpId/uVyyIIzF/awqCd3sDeadpUPO8GoMZQln1EiuJypX8Nadf/Heyd/vGibtDnCMcO8Ht6s//gWd/6SNdPYGatVyT9eMRvwdBSpU8mGNM6PJXOcYao4MRLAr1rug5SJhTvznXFekq5OZjwSXaoheUbDDaH8v5aqwJakeV2TtQYi6ud+b9CCybaZkyJNp4Ek14wQh84R+y71Uw5Q9tNqzrCCKJ+U0O3fWTOR2Dn4xkWBggfNu8YQKBgQDkPvjkAFN/lJpBF1XDY2CJMUAD+/hvVKrBsND/i6ohn4iDLf/83rXtVLXH36BZbUb7+IrJ1wr2qIJ/h1K6bMgwZyHME6zKrBCS1bZvdYpkOOHMuIaisul42+Rlb2BXHihHVtvdLMTsNVImKi5MuLlBvRuPPVved5TQ18EJUEWC0QKBgQC3NrgoWnZwGeMEOrE2KiINnbmEP1eSwI6AHv5m3uwY6TmbcHhqRyj956n4f076iKeUcWl6RkQz7bxlcjMs1wiTIKqDuTmKAvfLHmKzQdL1oOQ1T8dLJlWXojSa0cKnt1TXXqUC0NN5xAVBwn+jHdYUeCemXRRlakbTianyPb1TfwKBgEjNbUYMdJW1KJ6qesif4iLgerLKpCuerfiqFX/tZI7k+/4bphNaVl0lL/ZY9iSQHpwwYtSOqwiSJ03WNCUSnagSvU0C2ZKr3312fYJ/02y0WBGcqhUrTB0oxmk0ZV5kWCSpJ+gcZ5OQTmut+KawJSc60peV0r/bFLSonQIDgKiBAoGAHsmmNrnE71+aQ4qtXuHDqTAZDb0rNTEAgU00CQtq92Cx2ooS4iElJU25xVV3ayhtqMdKJ08JhQRtRUrkiKN2AGtb3BjTL3sCMvLfOSpVjgtEbiUC44EEnx+V4XJgWJi5PBvedNOsxeiHzZ4mnr2TzQrH9u/rToOGdWPL2DZBy3cCgYEAxNClrzhFvKBjiINBzYutl/ip/eqapaZf/VQ98rUJ6HY7aMT62QoP/iaHKrB6UVMKFxZkvcXBFiheljCGEFq5NNT2vd1UEvuqpPiAB+Xa5u3FciGw3eB6cL6KXVkXjd76LtluEpFKadXsfebnRNBZSXBOYueWYI7XoG/9yAJm0fo=

  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2vKq+TyrdcHfDpkSEhP3I8oSPrdSBban6FqJ4myPAYDLo9r8QKfbGQiTrZ0QHU2YlyXbBCFK2cLaG6fWfBHFSIDkx3x9GUEIqCdVTK/++P2nwDPM7k/Z+jOrpXnIWngMLMAwaMV6LEb2fbG+9kkS2Rq08vqb81Vys0VyT5WKbCeaaLLTZH1S6xCLa42SvfJ46+KZokfgVop997f9hViu8dAapfgS87dozlyLZIE10R7WIrvwPCd6jVf1ba0I+SnJRM5QlmIer4b8OBo0bI5Foi0ywHF6yLW/IiKpuHSc2ECln5L2ffdVeuTpp/hkUA6fF9P/VIYvWOSxPcVjBSAdxwIDAQAB

  #支付网关配置，这一项是写死的，正式环境是openapi.alipay.com
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  #支付成功之后的回调页面，只是一个友好页面。主要换成你自己映射的临时域名
  returnUrl: http://localhost:80/order/list
  #支付成功的接口回调，我们还没写，先空着
  notifyUrl: http://lupus.free.idcfengye.com/order/update
  signType: RSA2
  charset: utf-8


ngrok:
  后端: 15920e949045e8f5
  前端: 7622b422b1344cb1